services:
  - type: web
    name: degenome-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python migrate.py && uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PINATA_API_KEY
        sync: false
      - key: PINATA_SECRET_API_KEY
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: STORJ_ENDPOINT
        sync: false
      - key: STORJ_ACCESS_KEY
        sync: false
      - key: STORJ_SECRET_KEY
        sync: false
      - key: STORJ_BUCKET
        sync: false
      - key: ENVIRONMENT
        value: production
